# Generated by Django 6.0.8 on 2026-08-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hyd_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('eligibility', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
