# Generated by Django 6.0.8 on 2026-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyd_jobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hyd_jobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hyd_jobs',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hyd_jobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
